config/routes.rb
Rails.application.routes.draw do

  root 'pages#entryhandling'

  get 'entryhandling' => 'pages#entryhandling'
  get 'entryreport' => 'pages#entryreport'

  get 'search' => 'visitors#search'
  get 'choose' => 'visitors#choose'

  get 'new' => 'visitors#new'

  get 'changedate' => 'histories#changedate'

  resources :visitors
  resources :histories

end

app/models/gabinete.rb
class Gabinete < ActiveRecord::Base
end

app/models/headshot_photo.rb
class HeadshotPhoto < ActiveRecord::Base
  attr_accessible :description, :image_content_type, :image_file_name, :image_file_size, :image_updated_at

  belongs_to :capturable, :polymorphic => true

  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/history.rb
class History < ActiveRecord::Base
	has_one :gabinete
	belongs_to :visitor
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  scope :like, -> (q) { where 'nome LIKE ?', "#{q}%" }  
  
  has_many :history

  validates_presence_of :avatar, :nome
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
	
	def create
		v = Visitor.find(params[:history][:visitor_id])
		v.toggle(:in_building)
		v.save!
		
		if History.create history_params
			redirect_to root_url, message: 'Visita cadastrada'
		else
			redirect_to root_url, error: 'Nao foi possivel cadastrar a visita'
		end
	end

	def changedate
		session[:day] = day_params[:movement]
		redirect_to entryreport_url
	end

	private
	def history_params
		params.require(:history).permit(:visitor_id, :motivo, :gabinete_id, :tipo)
	end
	def day_params
		params.permit(:movement)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def entryhandling
    # session[:currentvisitor] = nil
    # session[:visitors] = nil

    @history = History.new
    @histories = History.where created_at: (Time.now.beginning_of_day..Time.now.end_of_day) 

    @gabinetes = Gabinete.all

    if session[:currentvisitor]
      @currentvisitor = Visitor.find(session[:currentvisitor]) 
    else
      @currentvisitor = Visitor.new
    end
    if session[:visitors]
      @visitors = Visitor.find(session[:visitors])
    else
      @visitors = []
    end

    @inBuilding = Visitor.where in_building: true

    render 'entryhandling'
  end

  def entryreport
    @day = Time.now || Time.parse(session[:day])

    @histories ||= History.where created_at: (@day.beginning_of_day..@day.end_of_day)

    render 'entryreport'
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def search
    if params[:q].length > 0
      session[:visitors] = Visitor.select('id').like(params[:q]).map { |v| v.id }
    else
      session[:visitors] = nil
    end
    redirect_to root_url
  end

  def choose    
    session[:currentvisitor] = params[:id]
    
    redirect_to root_url
  end

  def new
    session[:currentvisitor] = nil
    redirect_to root_url
  end

  def update
    visitor = Visitor.find(params[:id])
    visitor.update!(visitor_params)
    redirect_to(root_url)
  end

  def create  
    v = Visitor.new visitor_params
    v.in_building = false  
    if !v.save
      flash[:error] = "Usuário não pôde ser salvo, alguns parâmetros estão faltando"
    else
      session[:currentvisitor] = v.id
    end  
    redirect_to root_url
  end

  private
  def visitor_params
    params.require(:visitor).permit(:nome, :documento, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def isSearching
    return false
  end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-target="menu" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img alt="PRPB - Aplicações" src="/images/brasao2.gif" height="35"/>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="menu">
            <ul class="nav navbar-nav">
                <li class="<%= url_for request.fullpath == '/' ? 'active' : '' %>
                           <%= url_for request.fullpath == '/entryhandling' ? 'active' : '' %>">                   
                  <%= link_to 'Cadastro de Acesso', entryhandling_path %>
                </li>
                <li class="<%= url_for request.fullpath == '/entryreport' ? 'active' : '' %>">
                  <%= link_to 'Relatório de Visitantes', entryreport_path %>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EntradaSaida</title>
  <link type="image/x-icon" rel="shortcut icon" href="<%= asset_path 'favicon-96x96.png' %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/nav" %>

<div class="container main-row fade in out">
	<% if flash[:error] || flash[:message] %>
	<div class="alert <%= flash[:error] ? 'alert-danger' : 'alert-notice' %>">
	  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= flash[:error] || flash[:message] %>
		<script>
			window.setTimeout($("#alert").destroy(),2000);
		</script>
	</div>
	<% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/entryhandling.html.erb
<div class="col-md-9"> 
 <div class="row well">
    <div class="col-md-4">
      <%= render "components/search" %>
    </div>

    <div class="col-md-5 col-md-offset-2">    
      <a class='btn col-xs-5 col-xs-offset-3' href="/new">Novo Visitante</a>
      <%= render "partials/entry_data" %>
      <%= render "partials/mov_data" %>
    </div>
  </div>
</div>
<div class="col-md-2 col-md-offset-1 well">
  <%= render "components/in_building" %>    
</div>

app/views/pages/entryreport.html.erb
<div class="row well">
  <div class="page-header text-center">
    <div class="col-sm-6">
      <h4>Movimentação por Dia</h4>
    </div>
    <div class="col-sm-6">
      <%= form_tag '/changedate', method: 'get', id: 'changedate' do %>
        <div class="input-group" id="datetimepicker">
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          <%= text_field_tag :movement, nil, class: 'form-control', placeholder: 'Anteriores', id: 'movement' %>
          <!-- <input class="form-control" id="movement" placeholder="Anteriores" type="text"/> -->
        </div>
      <% end %>
    </div>
  </div>
  <table class="table table-hover table-striped">
    <thead>
    <tr>
      <th>Hora</th>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Motivo</th>
    </tr>
      <% @histories.each do |h| %>
        <tr>
          <td><%= h.created_at %></td>
          <td><%= h.visitor.nome %></td>
          <td><%= h.tipo %></td>
          <td><%= h.motivo %></td>
        </tr>
      <% end %>
    </thead>
  </table>

  <script>
    $(function () {
      $('#datetimepicker').datetimepicker({
        format: 'DD/MM/YYYY'
      }).on('dp.change', function (e) {
        if (e.oldDate)
          $('#changedate').submit();
      });
    })
  </script>
</div>

app/views/partials/_entry_data.html.erb
<div class="page-header text-center">
  <h4>Detalhes</h4>
</div>
<%= form_for @currentvisitor do |v| %>
  <table class="table table-striped table-hover">
    <%= v.text_field 'nome', class: 'form-control form-control-visitor', placeholder: 'Nome' %>
    <%= v.number_field 'documento', class: 'form-control form-control-visitor', placeholder: 'Documento' %>
    <% if @currentvisitor.persisted? %>  
      <img class="form-control-visitor" src="<%= @currentvisitor[:avatar] %>" />
    <% else %>
      <%= v.hidden_field 'avatar' %>
      <div class="form-control-visitor" id="tirar" class="form-control-visitor" >
        <div id="camera" style="width: 310px; height: 232px"></div>
          <p class="text-center">
            <a href="javascript:void(take_photo())">Tirar Foto</a>
          </p>
      </div>
      <div id="alterar" class="form-control-visitor">
        <div id="result"></div>
        <p class="text-center">
          <a href="javascript:void(take_photo())">Outra Foto</a>
        </p>
      </div>
      <%= javascript_include_tag 'wcam' %>
    <% end %>
    <div class="input-group col-xs-12 form-control-visitor"> 
      <% unless @currentvisitor.persisted? %>
        <button class="btn btn-danger"><a href="/new" class="a-unstyled">Cancelar</a></button>
      <% end %>
      <%= submit_tag @currentvisitor.persisted? ? 'Editar' : 'Adicionar', class: "btn btn-primary #{@currentvisitor.persisted? ? 'col-xs-offset-4 col-xs-4' : ' pull-right'}" %>
    </div>
  </table>
<% end %>

app/views/partials/_mov_data.html.erb
<% if @currentvisitor && @currentvisitor.persisted? %>

  <div class="page-header text-center">
    <h4>Movimentação</h4>
  </div>



  <%= form_for @history, class: 'entryForm' do |f| %>
    
    <%= f.hidden_field :visitor_id, value: @currentvisitor[:id] %>

    <%= f.hidden_field :tipo, value: Visitor.find(@currentvisitor[:id])[:in_building] ? 'Saida' : 'Entrada' %>

    <% unless @currentvisitor.in_building %>
      <%= f.label :motivo %>

      <%= f.text_field :motivo, class: 'form-control', placeholder: 'Motivo' %>

      <%= f.label :gabinete_id %>

      <%= f.select :gabinete_id, options_from_collection_for_select(@gabinetes, 'id', 'procurador'), {}, class: 'form-control' %>
    <% end %>
    <%= f.submit "Cadastrar #{@currentvisitor.in_building ? 'Saída' : 'Entrada'}", class: 'btn btn-default center-block form-control' %>

  <% end %>
<% end %>
<div class="page-header text-center">
  <h4>Últimas movimentações</h4>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Hora</th>
      <th>Nome</th>
    </tr>
  </thead>
 
  <tbody>
    <% @histories.each do |h| %>
      <tr>
        <td><%= h.created_at %> (<%= h.tipo %>)</td>
        <td><%= h.visitor.nome %></td>
      </tr>
    <% end %>
  </tbody>
</table>